# charts/my-node-app/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "my-node-app.fullname" . }}
  labels:
    app: {{ include "my-node-app.name" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "my-node-app.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "my-node-app.name" . }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "my-node-app.fullname" . }}
  labels:
    app: {{ include "my-node-app.name" . }}
spec:
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 3000
  selector:
    app: {{ include "my-node-app.name" . }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "my-node-app.fullname" . }}
  labels:
    app: {{ include "my-node-app.name" . }}
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/tags: key=value
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP":80,"HTTPS":443}]'
spec:
  rules:
    - host: {{ .Values.ingress.hosts[0].host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "my-node-app.fullname" . }}
                port:
                  number: {{ .Values.service.port }}
